openapi: "3.0.0"
info:
  title: "Book-Review-System API"
  version: 1.0
contact:
  email: kajal@gmail.com
liscence:
  name: Apache 2.0
  url: "http://apache.org/"
servers:
  - url: http://localhost:5000
    description: Development server
  # - url: https://api.gigantic-server.com/v1
  #   description: Production server

components:
  securitySchemes:
    CookieAuth:
        type: apiKey
        in: cookie
        name: token
    BearerAuth: 
        type: http
        scheme: bearer

paths:
  /signup:
    post:
      summary: Signup the user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
               username:
                required: true
                type: string
               email:
                required: true
                type: string
               password:
                required: true
                type: string
               dateOfBirth:
                type: string
                format: date
               role:
                type: string
              
                
      responses:
        '200':
          description: Successful signup response

  /login:
    post:
      summary: login the user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string    
      responses:
        '200':
          description: Successful login response

  /verify:
    post:
      summary: Verify the user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string    
      responses:
        '200':
          description: Successful verify response


  /addBooks:
    post:
      summary: Post Books
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string 
                author_name:
                  type: string    
                       
      responses:
        '200':
          description: Successful verify response

  /update-book/{id}:
    put:
      summary: Update books
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int64
               properties:
                 title:
                   type: string
                description:
                   type: string 
                author_name:
                   type: string    
                       
      responses:
        '200':
          description: Successful verify response


  /delete-book/{id}:
    delete:
      summary: Delete Books
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int64
             
      responses:
        '200':
          description: Successful verify response

  /addReview:
    post:
      summary: Add review
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                book_id:
                  type: string 
                review:
                  type: string    
                       
      responses:
        '200':
          description: Successful verify response

  /edit-review/{id}:
    put:
      summary: Edit review
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int64
               properties:
                 user_id:
                  type: string
                book_id:
                  type: string 
                review:
                  type: string    
                       
      responses:
        '200':
          description: Successful verify response

  /delete-review/{id}:
    delete:
      summary: Delete the review
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int64
             
      responses:
        '200':
          description: Successful verify response

  /add-rating:
    post:
      summary: Add rating
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                book_id:
                  type: string 
                rating:
                  type: string    
                       
      responses:
        '200':
          description: Successful verify response

  /edit-rating/{id}:
    put:
      summary: Edit rating
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int64
               properties:
                rating:
                  type: string    
                       
      responses:
        '200':
          description: Successful verify response

  /delete-rating/{id}:
    delete:
      summary: Delete rating
      parameters:
        - name: id
          in: path
          description: ID of the book to update
          required: true
      security:
      - BearerAuth: [] 
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int64
             
      responses:
        '200':
          description: Successful verify response


  /average:
    get:
      summary: To get average of ratings 
      requestBody:
        content:
          application/json:
            schema:
              type: object
                
                       
      responses:
        '200':
          description: Successful verify response
